#!/bin/sh

#kill -HUP `cat /var/run/shop_uwsgi.pid`
uwsgi --reload /var/run/shop_uwsgi.pid


#killall -9 uwsgi
#killall -9 uwsgi

#export LANG='ru_RU.UTF-8'
#export LC_ALL='ru_RU.UTF-8'

#/usr/local/bin/uwsgi --ini /etc/nginx/sp_uwsgi.ini