"""
Django settings for a project.

Generated by 'django-admin startproject' using Django 2.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'fl%fy=62yf0_@s$l!+r5=*1q)*bdke*cbn57c*04x7#lkxjn$o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

#DEFAULT_FROM_EMAIL = 'info@babah24.ru'
SERVER_EMAIL = 'discoroveryx@gmail.com'
ADMINS = [('disc', 'discoroveryx@gmail.com'),]


# Application definition

INSTALLED_APPS = [
	'acl',
	'node',
	'shopapp',
	#'newsapp',
	'panel',
	#
	'rest_framework',
	'captcha',
	'imagekit',
	'ckeditor',
	'corsheaders', #django-cors-headers
	'django_unused_media',
	#'django_cleanup',
	#'locale', 
	#'modeltranslation',
	'django_extensions',
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'django.contrib.postgres', #for *.objects.filter(search__*='*')
	#
	#'aldjemy',
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	#django-cors-headers
	'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'dj.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': ['template',],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'dj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.postgresql_psycopg2', #'ENGINE': 'django.db.backends.postgresql',
		'NAME': 'shop', #после восстановления от 031217 старая crm новая будет crm2
		'USER': 'shop',
		'PASSWORD': 'shop',
		'HOST': '94.73.245.253',
		'PORT': '5433',
	}
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'ru'

LANGUAGES = (
	('ru', u'Русский'),
	#('en', 'English'),
)

TIME_ZONE ='Asia/Krasnoyarsk'

USE_I18N = True

USE_L10N = True

USE_TZ = False

DATE_INPUT_FORMATS = ['%d-%m-%y','%d-%m-%Y']

LOGIN_URL = '/user/login'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

#STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'), )
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


#EMAIL settings
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'shop@babah24.ru'
EMAIL_HOST_PASSWORD = 'XXXXXXXX'
EMAIL_USE_SSL = True

#######################
######API TOKEN########
#
MAKEAPITOKEN_TOKEN='XXXXXXXXX' #dj.views makrapitoken
#
# MAKEAPITOKEN_1C_TOKEN='XXXXXXXXXX' #dj.views makrapitoken_1c
# #sms.views sms4b
# SMS4B_APILOGIN='babah24'
# SMS4B_APIPASSWD='[jhjibqgfhjkm'
# SMS4B_APISENDER='babah24.ru'
# #
# MOBILON_TOKEN='km2WVHzq9IjFCSr' #call.views call.mobilon
# WEBHOOKAUTHKEY='so34ke98rt' #call.mobilon


###test email sendpython
###python -m smtpd -n -c DebuggingServer localhost:1025
#EMAIL_HOST='localhost'
#EMAIL_PORT=1025

#django-cors-headers

CORS_ORIGIN_WHITELIST = (
	'94.73.245.253',
	'62.109.29.220',
	'185.63.191.218',
	'babah24.ru',
	'www.babah24.ru',
	'crm.babah24.ru',
	'www.crm.babah24.ru',
	'file.babah24.ru',
	'www.file.babah24.ru',
	'test.babah24.ru',
	'shop.babah24.ru',
	'www.shop.babah24.ru',
)

#CORS_ORIGIN_ALLOW_ALL = False

CKEDITOR_UPLOAD_PATH = os.path.join(BASE_DIR, "static")
CKEDITOR_CONFIGS = {
	'default': {
	'toolbar': [
	['Undo', 'Redo',
	'-', 'Bold', 'Italic', 'Underline',
	'-', 'Link', 'Unlink', 'Anchor', 'Image',
	'-', 'Format',
	'-', 'SpellChecker', 'Scayt',
	'-', 'Maximize',
	'-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock',
	],
	['HorizontalRule',
	'-', 'Table',
	'-', 'BulletedList', 'NumberedList',
	'-', 'Cut','Copy','Paste','PasteText','PasteFromWord',
	'-', 'SpecialChar',
	'-', 'Source',
	]
	],
}
}



#template_debug
#INSTALLED_APPS += ('template_debug',)
#TEMPLATE_DEBUG = True




# #debug-toolbar
# INSTALLED_APPS += ('debug_toolbar',)
# MIDDLEWARE_CLASSES += ('debug_toolbar.middleware.DebugToolbarMiddleware',)
# #TEMPLATE_DIRS += ['/usr/local/lib/python2.7/dist-packages/debug_toolbar/templates/debug_toolbar']
# INTERNAL_IPS = (
	# '127.0.0.1', 
	# #'94.73.245.253',
# )
# DEBUG_TOOLBAR_CONFIG = {
	# #'SHOW_TOOLBAR_CALLBACK': 'panel.views.django_debugtoolbar_show',
	# 'SHOW_COLLAPSED': True,
# }
# DEBUG_TOOLBAR_PANELS = [
	# #'debug_toolbar.panels.versions.VersionsPanel',
	# 'debug_toolbar.panels.timer.TimerPanel',
	# 'debug_toolbar.panels.settings.SettingsPanel',
	# 'debug_toolbar.panels.headers.HeadersPanel',
	# 'debug_toolbar.panels.request.RequestPanel',
	# 'debug_toolbar.panels.sql.SQLPanel',
	# #'debug_toolbar.panels.staticfiles.StaticFilesPanel',
	# 'debug_toolbar.panels.templates.TemplatesPanel',
	# #'debug_toolbar.panels.cache.CachePanel',
	# 'debug_toolbar.panels.signals.SignalsPanel',
	# 'debug_toolbar.panels.logging.LoggingPanel',
	# #'debug_toolbar.panels.redirects.RedirectsPanel',
# ]



# #django-bleach
# INSTALLED_APPS += (
	# 'django_bleach',
# )
# BLEACH_ALLOWED_TAGS = ['p', 'b', 'i', 'u', 'em', 'strong', 'br', 'font']
# BLEACH_STRIP_TAGS = True


#django-modeltranslation
#MODELTRANSLATION_DEFAULT_LANGUAGE = 'ru'


# CACHES = {
	# 'default': {
		# 'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
	# }
# }



#CATCHA SETTINGS
CAPTCHA_FONT_SIZE = 40
CAPTCHA_BACKGROUND_COLOR = '#ffffff'
CAPTCHA_FOREGROUND_COLOR = '#ff6600'
CAPTCHA_NOISE_FUNCTIONS = ('captcha.helpers.noise_dots',)
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.math_challenge'
CAPTCHA_LETTER_ROTATION = (-1, 1)
########################


REST_FRAMEWORK = {
	'DEFAULT_AUTHENTICATION_CLASSES': (
		'rest_framework.authentication.BasicAuthentication',
		#'rest_framework.authentication.SessionAuthentication',
	)
}



#LOGGING
LOGGING = {
	'version': 1,
	'disable_existing_loggers': False,
	'formatters': {
		'verbose': {
			#'format': '%(levelname)s %(asctime)s %(module)s %(name)s %(message)s'
			#'format': '%(levelname)s %(asctime)s %(name)s %(pathname)s %(process)d	 %(processName)s %(threadName)s %(message)s'
			'format': '[%(levelname)s %(asctime)s %(pathname)s] %(message)s',
			'datefmt': '%d-%m-%y %H:%M',
		},
		'simple': {
			'format': '%(levelname)s %(message)s'
		},
	},
	# 'filters': {
		# 'require_debug_false': {
			# '()': 'django.utils.log.RequireDebugFalse'
		# }
	# },
	'handlers': {
		# 'console': {
			# 'level': 'DEBUG',
			# 'class': 'logging.StreamHandler',
			# #'formatter': 'simple'
		# },
		# 'mailadmins': {
			# 'level': 'ERROR',
			# 'filters': ['require_debug_false'],
			# 'class': 'django.utils.log.AdminEmailHandler'
		# },
		# 'logerror': {
		# 	'level': 'WARNING',
		# 	#'filters': ['require_debug_false'],
		# 	#'formatter': 'verbose',
		# 	'maxBytes': 1024*1024*5, # 5 MB
		# 	'backupCount': 5,
		# 	'class': 'logging.handlers.RotatingFileHandler',
		# 	'filename': os.path.join(BASE_DIR, 'na_log/error.log'),
		# },
		# 'logsql': {
			# 'level': 'DEBUG',
			# #'filters': ['require_debug_false'],
			# #'formatter': 'verbose',
			# 'maxBytes': 1024*1024*5, # 5 MB
			# 'backupCount': 5,
			# 'class': 'logging.handlers.RotatingFileHandler',
			# 'filename': os.path.join(BASE_DIR, 'na_log/sql.log'),
		# },
		# 'logmain': {
		# 	'level': 'DEBUG',
		# 	#'filters': ['require_debug_false'],
		# 	'formatter': 'verbose',
		# 	'maxBytes': 1024*1024*5, # 5 MB
		# 	'backupCount': 5,
		# 	'class': 'logging.handlers.RotatingFileHandler',
		# 	'filename': os.path.join(BASE_DIR, 'na_log/main.log'),
		# },
		# 'acl': {
		# 	'level': 'INFO',
		# 	#'filters': ['require_debug_false'],
		# 	'formatter': 'verbose',
		# 	'maxBytes': 1024*1024*5, # 5 MB
		# 	'backupCount': 5,
		# 	'class': 'logging.handlers.RotatingFileHandler',
		# 	'filename': os.path.join(BASE_DIR, 'na_log/acl.log'),
		# },
		# 'shopapp': {
		# 	'level': 'INFO',
		# 	#'filters': ['require_debug_false'],
		# 	'formatter': 'verbose',
		# 	'maxBytes': 1024*1024*5, # 5 MB
		# 	'backupCount': 5,
		# 	'class': 'logging.handlers.RotatingFileHandler',
		# 	'filename': os.path.join(BASE_DIR, 'na_log/shopapp.log'),
		# },
		# 'newsapp': {
		# 	'level': 'INFO',
		# 	#'filters': ['require_debug_false'],
		# 	'formatter': 'verbose',
		# 	'maxBytes': 1024*1024*5, # 5 MB
		# 	'backupCount': 5,
		# 	'class': 'logging.handlers.RotatingFileHandler',
		# 	'filename': os.path.join(BASE_DIR, 'na_log/newsapp.log'),
		# },
	},
	'loggers': {
		# 'django': {
		# 	#'handlers': ['logmain', 'mailadmins',],
		# 	'handlers': ['logerror',],
		# 	'level': 'WARNING',
		# 	'propagate': True,
		# },
		# 'django.request': {
		# 	#'handlers': ['logmain', 'mailadmins',],
		# 	'handlers': ['logerror',],
		# 	'level': 'WARNING',
		# 	'propagate': True,
		# },
		# 'django.db.backends': {
			# 'handlers': ['logsql',],
			# 'level': 'DEBUG',
			# 'propagate': True,
		# },
		# 'acl': {
		# 	'handlers': ['acl',],
		# 	'level': 'INFO',
		# 	'propagate': True,
		# },
		# 'shopapp': {
		# 	'handlers': ['shopapp',],
		# 	'level': 'INFO',
		# 	'propagate': True,
		# },
		# 'newsapp': {
		# 	'handlers': ['newsapp',],
		# 	'level': 'INFO',
		# 	'propagate': True,
		# },
	}
}
